#EXERCISE 3.13

1. CREATE TABLE EMP
	(E# CHAR(4) NOT NULL,
		ENAME CHAR(4) NOT NULL,
		AGE SMALLINT,
		SEX CHAR(6),
		ECITY CHAR(100),
		PRIMARY KEY(E#));

	CREATE TABLE WORKS
	(E# CHAR(4) NOT NULL,
		C# CHAR(4) NOT NULL,
		SALARY INT NOT NULL,
		PRIMARY KEYS(E#, C#),
		FOREIGN KEY(E#)REFERENCES EMP(E#),
		FOREIGN KEY(C#)REFERENCES COMP(C#));

	CREATE TABLE COMP
	(C# CHAR(4) NOT NULL,
		CNAME CHAR(4) NOT NULL,
		CITY CHAR(4) NOT NULL,
		PRIMARY KEY(C#));

2. SELECT E#, ENAME
	FROM EMP
	WHERE SEX = 'MALE' AND AGE > '50'

3. SELECT EMP.E#, ENAME
	FROM EMP, WORKS
	WHERE WORKS.SALARY > '1000' AND WORKS.E# = EMP.E#

4. SELECT EMP.E#, ENAME
	FROM EMP, WORKS AS X, WORKS AS Y, COMP
	WHERE EMP.E# = X.E# AND EMP.E# = Y.E# AND X.C# = 'C4' AND Y.C = 'C8'

5. SELECT EMP.E#, ENAME
	FROM EMP, WORKS, COMP
	WHERE EMP.E# = WORKS.E# AND WORKS.C# = COMP.C# AND COMP.CNAME = 'LIANHUA' AND WORKS.SALARY > 1000

6. SELECT EMP.E#, COUNT(*) AS NUM, SUM(SALARY) AS SUM_SALARY
	FROM EMP, WORKS
	WHERE EMP.E# = WORKS.E#
	GROUP BY EMP.E#

7. SELECT EMP.E#
	FROM EMP
	WHERE EMP.E# = WORKS.E# AND WORKS.C# IN (SELECT C#
												FROM WORKS 
												WHERE WORKS.E# = 'E6')

8. SELECT EMP.E#, EMP.ENAME
	FROM EMP, WORKS
	WHERE WORKS.E# = EMP.E# AND WORKS.SALARY < (SELECT AVG(SALARY)
													FROM WORKS
													WHERE WORKS.C# = COMP.C# AND COMP.C# = 'LIANHUA')

9. UPDATE WORKS
	SET WORKS.SALARY = WORKS.SALARY + 100
	WHERE WORKS.E# = EMP.E# AND EMP.AGE > 50

10. DELETE FROM EMP, WORKS
	WHERE EMP.E# = WORKS.E# AND EMP.AGE > 60																	