#exercise 3.2

1.  SELECT S#, SNAME
	FROM S
	WHERE AGE<'17';

2.  SELECT C.C#, C.CNAME
	FROM C, S
	WHERE S.SEX='MALE'

3.  SELECT T#, TNAME
	FROM T
	WHERE T# IN 
		(SELECT T#
		FROM C
		WHERE C# IN
			(SELECT C#
			FROM SC, S
			WHERE S.S# = 'MALE'))

4.  SELECT S#
	FROM SC
	WHERE S# NOT IN 
		(SELECT S#
		FROM S, SC
		WHERE S.S#=SC.S#)
		AND S# NOT IN
		(SELECT S#
		FROM S, SC
		WHERE UNIQUE(SELECT S#
					FROM S, SC
					WHERE S.S#=SC.S#))
5.  SELECT X.C#
	FROM SC AS X, SC AS Y
	WHERE X.C#=Y.C# AND X.S# = 'S2' AND Y.S# = 'S4'

6.  SELECT C.C#
	FROM SC, C
	WHERE SC.S# NOT IN
		(SELECT C#
		FROM SC
		WHERE SC.S# <> 'WANG')

7.  SELECT C#, CNAME
	FROM C
	WHERE NOT EXISTS
		(SELECT *
		FROM S
		WHERE NOT EXISTS
			(SELECT *
			FROM SC
			WHERE SC.S#=S.S# AND SC.C# = C.C#)))

8.  SELECT S#
	FROM S AS X
	WHERE NOT EXISTS
		(SELECT *
		FROM C AS Y
		WHERE C.T# = 'LIU'
			AND NOT EXISTS
				(SELECT *
				FROM SC AS Z
				WHERE Y.C# = Z.C#
					AND S.S# = Z.S#))



