#exercise 3.7

1.  SELECT COUNT(*)
	FROM C
	WHERE C.C# NOT IN
		(SELECT C#
		FROM SC
		WHERE NOT EXISTS
			(SELECT *
			FROM SC
			WHERE SC.S#=S.S# AND SC.C#=C.C#))

2.  SELECT AVG(AGE)
	FROM S
	WHERE S.SEX = 'FEMALE' AND SC.C# = 'C4' AND S.S# = SC.S#

3.  SELECT CNAME, AVG(SCORE)
	FROM SC, C
	WHERE T.TNAME = 'LIU' AND T.T# = C.T# AND C.C# = SC.C#
	GROUP BY CNAME

4.  SELECT C#, COUNT(S#)
	FROM C, SC
	WHERE C.C# = SC.C#
	GROUP BY C#
	HAVING COUNT(*) > 10
	ORDER BY 2, C.C# ASC

5.  SELECT Y.SNAME
	FROM S AS X, S AS Y
	WHERE X.SNAME = 'WANG' AND Y.S# > X.S# AND Y.AGE < X.AGE

6.  SELECT S#, C#
	FROM SC
	WHERE SCORE = 'NULL'
	GROUP BY S#

7.  SELECT SNAME, AGE
	FROM S
	WHERE SNAME LIKE 'L%'
	GROUP BY SNAME

8.  SELECT SNAME, AGE
	FROM S
	WHERE SEX = 'MALE'
		AND AGE > (SELECT AVG(AGE)
					FROM S
					WHERE SEX = 'FEMALE')
	GROUP BY SNAME

9.  SELECT SNAME, AGE
	FROM S
	WHERE SEX = 'MALE'
		AND AGE > ALL (SELECT AGE
						FROM S
						WHERE SEX = 'FEMALE')